### ISSUE TITLE
Running the notebook results in 2 sets of buttons (add pane, import, export)

### ISSUE THREAD

**Issue by dkp** [DevinBayly/neuro-choro#14]
I see that there is only one set of buttons (add pane, export, import) until I run the notebook.  Then there are two sets of buttons.

**Comment by DevinBayly** [comment]
Very likely this is an iodide thing. The start application simply appends material to the application Holder div. If you run the notebook several times, several elements are added. I would recommend refreshes of the report view instead of running all cells multiple times. I don't think this will affect us outside of the development stage. Please reopen if you feel differently.
