### ISSUE TITLE
Interaction of "Alt column" and "selected region panel"

### ISSUE THREAD

**Issue by dkp** [DevinBayly/neuro-choro#38]
If I load LearnRuns.csv and click a region to see the region value for run1 (for example), the "selected region panel" is displayed.

If I switch the alt column to run2 and click the same region, the selected region panel disappears. Although it is the same region, it is a different value.  

Is it possible to switch the disappearance of the selected region panel to occur only if it is not an exact match?

**Comment by DevinBayly** [comment]
could you put some screen shots of this behavior in so its easier to recreate? I think I understand what you're talking about, but I want to make sure.

**Comment by dkp** [comment]
See the mp4 movie in Box: https://arizona.box.com/s/w8aezsjd1xogcdjy1238fptvdzjhfm2a
Description: The CSV contains all 4 runs.
Problem:  
-First I filter by run 1 (alt column filter).
-I select HG_R:
The selected region panel appears containing the mean for run1.
-Next, I switch the alt column filter to run2.
-I select HG_R:
**The selected region panel disappears.**

Expected Behavior: I should get a 2nd HG_R panel containing the mean for run2 and displayed alongside the 1st HG_R panel that displays the mean for run1.

**Comment by DevinBayly** [comment]
hmm movie appears to be gone. The behavior here is actually expected in that I have code checking the 1:1 mapping of region selection to tooltip creation. Secondly, there's a tight rational linkage between the content shown in the canvas at any time and the tooltips that are shown. as you have switched to a different filter, we are no longer looking at the same canvas as when the tooltip was first created for HG_R.

**Comment by DevinBayly** [comment]
do you mean though that this occurs when you select the HG_R run 2 on a separate pane? Because that would be a bug.

**Comment by DevinBayly** [comment]
AAH I contradicted myself. The tooltip should fully go away when you change the alt filter, and it doesn't. haha. I'm going to fix that, but its still not going to give you what you're looking for. Can you tell me what the benefit is of having multirun tooltips within a single pane vs, multiple panes multiple tooltips? Is it to save time making a second pane?

In this approach you undermine a design choice that I really feel strongly about which is to leverage "eyes over memory". when the canvas updates you no longer see all the information run 1 was presenting to you, all you have from that is the info in the tooltip. you might then find yourself going back and forth between runs using the alt column selection instead of doing what you previously did which was to lay out all the runs in separate panes and select common regions within each of them.

**Comment by dkp** [comment]
I guess I was trying to save time not creating another pane. I defer to your design choice.  These should be separate panes.

**Comment by dkp** [comment]
Apparently I didn't create the right kind of link in Box. The movie is tiny, so I'm attaching it.

BUT, I think you convinced me I was using it wrong.

If you are going to remove all region panels when the alt column gets changed, could you provide a warning first?  I can imagine being surprised and upset by the disappearance.

-D

________________________________
